config/routes.rb
Rails.application.routes.draw do

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  # admin
  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'

  resources :tasks do
    # 新規登録の確認画面 /tasks/new/confirm というURLをconfirm_newアクションに対応させる
    post :confirm, action: :confirm_new, on: :new
    # importアクションを追加する
    post :import, on: :collection
  end

end

app/models/task.rb
class Task < ApplicationRecord
  # before_validation :set_nameless_name

  # ページネーションの表示件数指定
  # paginates_per 50


  # 一つのタスクから一つの画像を紐付ける。Taskもでるからimageを呼ぶことを指定している。
  has_one_attached :image

  # validates :name, presence: true
  # validates :name, length: {maximum: 30}
  # validates :name, presence: true, length: {maximum: 30}

  validate :validate_name_not_including_comma

  # TaskとUserの関係は、多対1
  belongs_to :user

  # スコープ
  # recent(最近)という名前で登録
  scope :recent, -> {order(created_at: :desc)}


  # ransackable_attributes
  # 検索対象にすることを許可するカラムを指定
  def self.ransackable_attributes(auth_objest = nil)
    %w[name created_at]
  end

  # ransackable_associations
  # 検索条件を含める関連を指定。
  # これを、空に配列を返すようにオーバーライドすることで、検索条件に意図しない関連を含めないようにしてる。
  def self.ransackable_associations(auth_object = nil)
    []
  end


  # CSVデータをどの属性をどの順番で出力するかを得るメソッド
  def self.csv_attributes
    ["name", "description", "created_at", "updated_at"]
  end

  def self.generate_csv
    # CSV.generateで、CSVデータの文字列を生成します。
    CSV.generate(headers: true) do |csv|
      # CSVの１行目としてヘッダを出力する。ここでは属性名をそのまま見出しとして使ってる。
      csv << csv_attributes

      all.each do |task|
        # allメソッドで全タスクを取得し、１レコードごとにCSVの１行を出力します。
        # その際は属性ごとにTaskオブジェクトから属性値を取り出してcsvに与えている。
        csv << csv_attributes.map {|attr| task.send(attr)}
        # attrに属性が入ってるので、sendメソッドで、
        # task.name
        # task.description
        # task.created_at
        # task.updated_at
        # を、取り出してcsvに書き込んでる
      end
    end
  end


  # fileという名前の引数で、アップされたファイルの内容にアクセスするためのオブジェクトを受け取る
  def self.import(file)
    # CSV.foreachを使って、CSVファイルを一行ずつ読み込む。
    # header: trueの指定により、１行目をヘッダとして無視するようにする。
    CSV.foreach(file.path, headers: true) do |row|
      # CSV１行ごとに、Taskインスタンスを生成します。new はTask.newと同意です。
      # このクラスメソッドでは、selfがTaskの状態なので、省略してます。
      task = new
      # 生成したTaskインスタンスの各属性に、CSVの一行の情報を加工して入れ込みます。
      # slice railsがhashクラスに追加しているメソッド。指定した安全なキーに対応するデータだけを取り出して入力に用いるようにしている。
      # sliceに指定している csv_attributes は、csv_attributeメソッドに戻り値の配列内ｎ要素をそれぞれ引数に指定する書き方。
      # slice("name", "description", "created_at", "updated_at")と記述しているのと同じ意味
      task.attributes = row.to_hash.slice(*csv_attributes)
      # Taskインスタンスをデータベースに登録します。
      task.save!
    end
  end


  private

  # def set_nameless_name
  #   # blank?(nilや空白)の時に、'名前なし'を代入
  #   self.name = '名前なし' if name.blank?
  # end

  def validate_name_not_including_comma
    # include? 要素にオブジェクトが含まれていればtrue この場合は「,」
    # &. でnameがnilの場合に例外が発生することを避けるため。nilを返すために
    errors.add(:name, 'にカンマを含めることはできません。') if name&.include?(',')
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  before_action :set_task, only: [:show, :edit, :update, :destroy]


  def index
    # ジョブの呼び出し redisが動いてないとダメ
    # TestJob.perform_later

    # @tasks = Task.all
    # @tasks = current_user.tasks.order(created_at: :desc)

    # これも同じ
    # @tasks = Task.where(user_id: current_user.id)

    # scope recentを使う
    # @tasks = current_user.tasks.recent

    # ransackを使って検索機能
    @q = current_user.tasks.ransack(params[:q])
    # gem kaminariを使ってページネーション。
    # デフォルト25件。perで５０に設定。これはmodelでもできる。
    # @tasks = @q.result(distinct: true).page(params[:page]).per(50)
    @tasks = @q.result(distinct: true).page(params[:page])


    # 一覧表示のindexに、異なるフォーマットでの出力機能を用意する
    # respond_to 返却するレスポンスのフォーマットを切り替えるためのメソッド
    # format.htmlはHTMLとしてアクセスされた場合（URL拡張子なしでアクセスされた場合）
    # format.csvはCSVとしてアクセスされた場合（/task.csvというURLでアクセスされた場合）
    respond_to do |format|
      # HTMLフォーマットについては特に処理指定してない。から、デフォルト動作としてindex.htm.slimが表示される
      format.html
      # CSVフォーマットの場合はsend_dataメソッドをつかってレスポンスを送り出し、
      # 送り出したデータをブラウザからファイルとしてダウンロードできるようにします。
      # レスポンス内容は、Task.genarate_csvが生成するCSVデータとしています。
      # ファイル名は、ダウンロードするたびに異なるファイル名になるように、現在時刻をつかって作成してる。
      format.csv {
        send_data @tasks.generate_csv, filename: "tasks-#{Time.zone.now.strftime('%Y%m%dS')}.csv"
      }
    end
  end

  def show
    # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])
  end

  # 新規登録画面
  def new
    @task = Task.new
  end

  # 確認画面
  def confirm_new
    @task = current_user.tasks.new(task_prams)
    render :new unless @task.valid?
  end


  def create

    # オブジェクトを生成

    # merge 2つのハッシュの統合
    # @task = Task.new(task_prams.merge(user_id: current_user))

    # current_userのtaskにnewする
    @task = current_user.tasks.new(task_prams)

    # 上の2つ、どちらもログインしているユーザーのidをuser_idに入れた状態で、Taskデータに登録することができる。

    # 戻るボタンを押されたとき
    if params[:back].present?
      render :new
      return
    end

    # save!ではなくsaveを使う。戻り値によって制御をかえるため。save!だと例外を発生させるから。
    if @task.save

      # deliver_now 即時送信するメソッド
      TaskMailer.creation_email(@task).deliver_now
      # TaskMailer.creation_email(@task).deliver_now(wait: 5.minutes) # 5分後に送信

      # ジョブの呼び出し
      # perform_laterメソッド(ログ出力)で、非同期に実行。
      # ここでperform_laterは、ジョブの実行を予約するだけ（ジョブを登録するだけ）で、ジョブの開始や完了を待つことはない。
      # すぐに対応できない状態であれば、ジョブの処理は、処理できる状態になったら時点で開始される。
      SampleJob.perform_later
      # 翌日の正午ににジョブを実行
      # SampleJob.set(wait_unil: Date.tomorrow.noon).perform_later
      # 一週間後に実行
      # SampleJob.set(wait:1.week).perform_later


      # log関連

      # デバッグ用に、保存したタスクの情報をログに出力させたい場合。
      # logger.debug "タスク： #{@task.attributes.inspect}"
      # log/developments.log に出力
      logger.debug 'logger に出力'
      # logger.formatter.debug
      # log/custom.log に出力。なければ作成。
      Rails.application.config.custom_logger.debug 'custom_logger にも出力してる'
      # taskに関するログだけを専用ファイルに出力
      task_logger.debug 'taskのログを出力'

      flash[:notice] = "タスク「#{@task.name}」を登録しました。"
      redirect_to task_url @task
    else
      render :new
    end

  end


  def edit
    # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])
  end

  def update
    # task = Task.find(params[:id])
    # task = current_user.tasks.find(params[:id])
    @task.update!(task_prams)
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  def destroy
    # task = Task.find(params[:id]).destroy
    # task = current_user.tasks.find(params[:id]).destroy

    @task.destroy
    # redirect_to tasks_url, notice: "タスク「#{@task.name}を削除しました。」"

    # Ajax版
    # redirect_toの代わりにheadメソッドを用いて、レスポンスボディなしでHTTPステーラスとして204が返る（成功と判断される）
    # head :no_content
    # ↑ views/tasks.destroy.je.erbがビューとして出力されるように、コメントアウト

  end




  # オリジナルのロガー taskに関するログだけファイル出力
  def task_logger
    @task_logger ||= Logger.new('log/task.log', 'daily')
  end

  def import
    # アップロードされたファイルオブジェクトを引数に、関連越しにmodelに追加したimportメソッドを呼び出す。
    # これにより、アップロードされたファイルの内容を、ログインしているユーザーのタスク郡として登録することができる。
    current_user.tasks.import(params[:file])
    # インポートが終わったあとにタスク一覧画面に遷移する。
    redirect_to tasks_url, notice: "タスクを追加しました"
  end


  private

  # ストロングパラメーター
  def task_prams
    # permitで指定したものだけ変更を加える
    params.require(:task).permit(:name, :description, :image)
  end

  def set_task
    # params[:id]からタスクオブジェクトを検索して@taskに代入する
    @task = current_user.tasks.find(params[:id])
  end

end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/@index.html.erb
h1 タスク一覧

= search_form_for @q, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-outline-primary'

= link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

table.table.table.hover
  thead.thead-default
    tr
      / th= Task.human_attribute_name(:name)

      / デフォルトはcreated_atの降順でソート
      th= sort_link(@q, :name, default_order: :desc)

      / 基本的には名称でソートし、名称が同じであれば登録日時にソートする
      / th= sort_link(@q, :name, [:name, "created_at desc"])

      th= sort_link(@q, :created_at)
      / th= Task.human_attribute_name(:created_at)
      th
  tbody
    - @tasks.each do |task|
      tr id="task-#{task.id}"
        / td= link_to task.name, task_path(task)
        / 上と下は同じ。railsが、taskというオブジェクトから推測してくれる。
        td= link_to task.name, task
        td= task.created_at
        td
          = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
            / = link_to '削除', task, method: :delete, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

            / Ajax版
            / 削除リンクの目印として「.delete」を付与
          = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。OK?"}, class: 'btn btn-danger delete'

= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mb-3'
/ URLを生成する際にformat: :csv という指定をすることで、/tasks.csvというURLを生成している。

= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file
  = submit_tag "インポート", class: 'btn btn-primary'

app/views/tasks/_form.html.slim
- if task.errors.present?
  ul#error_explanation
    - task.errors.full_messages.each do |message|
      li= message

= form_with model: task, local: true do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  .form-group
    = f.label :image
    = f.file_field :image, class: 'form-control'

  = f.submit nil, class: 'btn btn-primary'

app/views/tasks/confirm_new.html.slim
h1 登録内容の確認

= form_with model: @task, local: true do |f|
  table.table.table-hover
    tbody
      tr
        th= Task.human_attribute_name(:name)
        td= @task.name
        = f.hidden_field :name
      tr
        th= Task.human_attribute_name(:description)
        td= simple_format(@task.description)
        = f.hidden_field :description
  = f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'
  = f.submit '登録', class: 'btn btn-primary'

app/views/tasks/destroy.js.erb
//destroyアクションに対応するテンプレートにjsを記述
document.querySelector("#task-<%= @task.id %>").style.display = 'none';

//rails-ujsでAjax通信を行う場合、レスポンスとしてJavaScriptga返されていれば、自動的にそれを実行してくれます。
//そのため、特に代わりの記述を追加せずに、これだけのタスクの非表示処理が動作する。

//サーバー側で動的にJSを組み立てることができることが利点

//例えば、削除と同時に「残りのタスクは○○件です」といったメッセージを表示することも簡単にできる。
var message = document.createElement('p');
message.innerText = 'タスク「<%= @task.name %>を削除しました。残りのタスクは<%= Task.count %>件です。」';
document.querySelector('title').insertAdjacentElement('beforebegin', message);


//railsでは、このようなサーバーサイドで生成したJSからなるレスポンス（またはこのレスポンスによる画面更新までのプロセス）のことを、
//Server-generated JavaScript Resopnses(SJR)といいます。

//メリット：手軽。テンプレートやヘルパー、モデルなどのサーバーサイドの資産を簡単に扱える。
//デメリット：１つの画面に関するJSがあちらこちらに散らばり、共通化しづらい。

app/views/tasks/edit.html.slim
h1 タスクの編集

.nav-justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}

app/views/tasks/index.html.slim
h1 タスク一覧

= search_form_for @q, url: tasks_path, class: 'mb-5' do |f|
  .form-group.row
    = f.label :name_cont, '名称', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :name_cont, class: 'form-control'
  .form-group.row
    = f.label :created_at_gteq, '登録日時', class: 'col-sm-2 col-form-label'
    .col-sm-10
      = f.search_field :created_at_gteq, class: 'form-control'

  .form-group
    = f.submit class: 'btn btn-outline-primary'

= link_to '新規登録', new_task_path, class: 'btn btn-primary mb-3'

.mb-3
  = paginate @tasks
  = page_entries_info @tasks

table.table.table.hover
  thead.thead-default
    tr
      / th= Task.human_attribute_name(:name)

      / デフォルトはcreated_atの降順でソート
      th= sort_link(@q, :name, default_order: :desc)

      / 基本的には名称でソートし、名称が同じであれば登録日時にソートする
      / th= sort_link(@q, :name, [:name, "created_at desc"])
      / 基本的には名称でソートし、名称が同じであれば登録日時にソートする
      / th= sort_link(@q, :name, [:name, "created_at desc"])

      th= sort_link(@q, :created_at)
      / th= Task.human_attribute_name(:created_at)
      th
  tbody
    - @tasks.each do |task|
      tr id="task-#{task.id}"
        / td= link_to task.name, task_path(task)
        / 上と下は同じ。railsが、taskというオブジェクトから推測してくれる。
        td= link_to task.name, task
        td= task.created_at
        td
          = link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'
          / = link_to '削除', task, method: :delete, data: {confirm: "タスク「#{task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'

            / Ajax版
            / 削除リンクの目印として「.delete」を付与
          = link_to '削除', task, method: :delete, remote: true, data: {confirm: "タスク「#{task.name}」を削除します。OK?"}, class: 'btn btn-danger delete'

= link_to 'エクスポート', tasks_path(format: :csv), class: 'btn btn-primary mb-3'
/ URLを生成する際にformat: :csv という指定をすることで、/tasks.csvというURLを生成している。

= form_tag import_tasks_path, multipart: true, class: 'mb-3' do
  = file_field_tag :file
  = submit_tag "インポート", class: 'btn btn-primary'

app/views/tasks/new.html.slim
h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'

= render partial: 'form', locals: {task: @task}


/ - if @task.errors.present?
/   ul#errors_explanation
/     - @task.errors.full_messages.each do |message|
/       li= message
/
/ = form_with model: @task, local: true, url: confirm_new_task_path do |f|
/   .form-group
/     = f.label :name
/     = f.text_field :name, class: 'form-control', id: 'task_name'
/   .form-group
/     = f.label :description
/     = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
/   = f.submit '確認', class: 'btn btn-primary'

app/views/tasks/show.html.slim
h1 タスクの詳細

.nav-justify-content-end
  = link_to '一覧', tasks_path, class: 'nav-link'
table.table.table-hover
  tbody
    tr
      th= Task.human_attribute_name(:id)
      td= @task.id
    tr
      th= Task.human_attribute_name(:name)
      td= @task.name
    tr
      th= Task.human_attribute_name(:description)
      / td= simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div")

      / auto_link版
      td= auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))
    tr
      / 画像
      th= Task.human_attribute_name(:image)
      / @task.image.attached? で実際に画像が添付されているときだけimage_tagを表示するようにしている
      td= image_tag @task.image if @task.image.attached?
    tr
      th= Task.human_attribute_name(:created_at)
      td= @task.created_at
    tr
      th= Task.human_attribute_name(:updated_at)
      td= @task.updated_at

= link_to '編集', edit_task_path(@task), class: 'btn btn-primary mr-3'
= link_to '削除', @task, method: :delete, data: {confirm: "タスク「#{@task.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'